# Autogenerated sitecustomize to apply safe LiteLLM runtime defaults
# This runs on interpreter startup for all Python processes using the venv
try:
    import importlib, importlib.util
    spec = importlib.util.find_spec("litellm")
    if spec is not None:
        litellm = importlib.import_module("litellm")
        if hasattr(litellm, "turn_off_message_logging"):
            try:
                litellm.turn_off_message_logging = True
            except Exception:
                pass
        if hasattr(litellm, "store_audit_logs"):
            try:
                litellm.store_audit_logs = False
            except Exception:
                pass
        if hasattr(litellm, "use_litellm_proxy"):
            try:
                litellm.use_litellm_proxy = False
            except Exception:
                pass
        # Wrap cold-storage object key generator to fail-closed
        try:
            from litellm.litellm_core_utils import litellm_logging as _litellm_logging
            payload_setup = getattr(_litellm_logging, "StandardLoggingPayloadSetup", None)
            original = getattr(payload_setup, "_generate_cold_storage_object_key", None)
            if payload_setup is not None and original is not None and not getattr(original, "_cerberus_safe_wrap", False):
                def _safe_generate_cold_storage_object_key(*args, **kwargs):
                    try:
                        return original(*args, **kwargs)
                    except Exception:
                        return None
                _safe_generate_cold_storage_object_key._cerberus_safe_wrap = True
                payload_setup._generate_cold_storage_object_key = staticmethod(_safe_generate_cold_storage_object_key)
        except Exception:
            pass
except Exception:
    pass
