"""Session shutdown command for Cerebro REPL.

This module replaces a bare process exit with a structured shutdown pipeline
for commercial engagements where auditability and integrity are mandatory.

Exports:
  - ``ShutdownOrchestrator``: utility class for graceful/forced shutdown.
  - ``ExitCommand``: ``FrameworkCommand`` command wrapper.
"""

from __future__ import annotations

import asyncio
import json
import os
import signal
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

from cerberus.repl.commands.base import FrameworkCommand, register_command


console = Console()


# ---------------------------------------------------------------------------
# Status models
# ---------------------------------------------------------------------------

@dataclass
class ShutdownReport:
    """Structured output generated by ``ShutdownOrchestrator``."""

    started_at: float
    finished_at: float = 0.0
    mode: str = "graceful"            # graceful | force
    memory_synced: bool = False
    workspace_synced: bool = False
    async_drained: bool = False
    orphaned_processes_cleaned: int = 0
    sensitive_buffers_cleared: bool = False
    critical_tool_failed: bool = False
    budget_exceeded: bool = False
    cost_usd: float = 0.0
    workspace_report_path: str = ""
    notes: List[str] = field(default_factory=list)

    @property
    def duration_seconds(self) -> float:
        if self.finished_at <= 0:
            return 0.0
        return max(0.0, self.finished_at - self.started_at)

    @property
    def exit_code(self) -> int:
        # Return code priority:
        # 2 -> budget exceeded, 1 -> critical tool failed, 0 -> clean exit
        if self.budget_exceeded:
            return 2
        if self.critical_tool_failed:
            return 1
        return 0


# ---------------------------------------------------------------------------
# Shutdown orchestrator
# ---------------------------------------------------------------------------

class ShutdownOrchestrator:
    """Coordinates secure, auditable session shutdown.

    Responsibilities:
    - Persist memory/workspace state.
    - End usage tracking and capture cost information.
    - Terminate orphaned background tool sessions.
    - Drain/cancel async tasks gracefully.
    - Clear sensitive in-memory buffers best-effort.
    - Produce a compact post-mortem report in the workspace.
    """

    def __init__(self, *, workspace: Any = None, memory: Any = None) -> None:
        self.workspace = workspace
        self.memory = memory
        self._start = time.time()
        self._sensitive_buffers: List[bytearray] = []

    # -- helpers ------------------------------------------------------------

    @staticmethod
    def _engagement_start_time() -> float:
        """Return process engagement start timestamp if available."""
        try:
            from cerberus.util import START_TIME  # type: ignore

            return float(START_TIME)
        except Exception:
            return time.time()

    @staticmethod
    def _format_hms(seconds: float) -> str:
        sec = int(max(0, seconds))
        hrs, rem = divmod(sec, 3600)
        mins, secs = divmod(rem, 60)
        return f"{hrs:02d}:{mins:02d}:{secs:02d}"

    @staticmethod
    def _call_sync_or_save(component: Any, label: str) -> Tuple[bool, str]:
        """Try common sync/save method names on a component."""
        if component is None:
            return False, f"{label}: unavailable"

        candidates = [
            "sync",
            "save",
            "flush_sync",
            "flush",
            "persist",
            "freeze",
            "archive",
            "close",
        ]

        for method_name in candidates:
            method = getattr(component, method_name, None)
            if callable(method):
                try:
                    method()
                    return True, f"{label}: {method_name}()"
                except TypeError:
                    # Method may require args; skip to next candidate.
                    continue
                except Exception as exc:  # pylint: disable=broad-except
                    return False, f"{label}: {method_name}() failed: {exc}"

        return False, f"{label}: no sync/save method"

    @staticmethod
    def _active_workspace_root() -> Path:
        """Resolve workspace path for post-mortem output."""
        try:
            from cerberus.tools.workspace import get_project_space

            return get_project_space().ensure_initialized().resolve()
        except Exception:
            return Path.cwd().resolve()

    @staticmethod
    def _read_cost_usd() -> float:
        """Read total session cost from known trackers."""
        try:
            from cerberus.util import COST_TRACKER

            return float(getattr(COST_TRACKER, "session_total_cost", 0.0) or 0.0)
        except Exception:
            pass

        try:
            from cerberus.repl.commands.cost import USAGE_TRACKER

            return float(USAGE_TRACKER.session_total())
        except Exception:
            return 0.0

    @staticmethod
    def _budget_exceeded() -> bool:
        try:
            from cerberus.repl.commands.cost import USAGE_TRACKER

            return bool(getattr(USAGE_TRACKER, "budget_exceeded", False))
        except Exception:
            return False

    @staticmethod
    def _critical_tool_failure_detected() -> bool:
        """Best-effort tool failure detection from active sessions/state flags."""
        if os.getenv("CERBERUS_CRITICAL_TOOL_FAILED", "").strip() in ("1", "true", "TRUE"):
            return True

        try:
            from cerberus.tools.sessions import ACTIVE_SESSIONS, SESSIONS_LOCK

            with SESSIONS_LOCK:
                for _, sess in list(ACTIVE_SESSIONS.items()):
                    proc = getattr(sess, "process", None)
                    if proc is not None:
                        rc = proc.poll()
                        if rc not in (None, 0):
                            return True

                    out_buf = getattr(sess, "output_buffer", [])
                    if out_buf and any("critical" in str(x).lower() for x in out_buf[-30:]):
                        return True
        except Exception:
            pass

        return False

    # -- cleanup stages -----------------------------------------------------

    async def _drain_async_tasks(self, timeout: float = 3.0) -> bool:
        """Cancel and gather pending asyncio tasks."""
        try:
            try:
                from cerberus.agents.run import Runner

                await Runner.shutdown_active_streams()
            except Exception:
                pass

            current = asyncio.current_task()
            tasks = [
                t for t in asyncio.all_tasks()
                if t is not current and not t.done()
            ]
            if not tasks:
                return True

            for task in tasks:
                task.cancel()

            done, pending = await asyncio.wait(tasks, timeout=timeout)
            if done:
                await asyncio.gather(*done, return_exceptions=True)
            if pending:
                for task in pending:
                    task.cancel()
                await asyncio.gather(*pending, return_exceptions=True)
            return True
        except Exception:
            return False

    async def _cleanup_orphaned_sessions(self) -> int:
        """Terminate active shell/tool sessions registered in session manager."""
        cleaned = 0
        try:
            from cerberus.tools.sessions import ACTIVE_SESSIONS, SESSIONS_LOCK, terminate_session

            with SESSIONS_LOCK:
                session_ids = list(ACTIVE_SESSIONS.keys())

            for sid in session_ids:
                try:
                    terminate_session(sid)
                    cleaned += 1
                except Exception:
                    # Fallback: continue with remaining sessions.
                    continue
        except Exception:
            pass

        # Also run the global shutdown coordinator for named process targets.
        try:
            from cerberus.agents.shutdown_coordinator import SHUTDOWN_COORDINATOR

            targets = os.getenv("CERBERUS_SHUTDOWN_TARGETS", "")
            target_list = [t.strip() for t in targets.split(",") if t.strip()]
            SHUTDOWN_COORDINATOR.shutdown(sigterm_targets=target_list or None)
        except Exception:
            pass

        return cleaned

    def _finalize_usage_tracking(self, cost_usd: float) -> None:
        """Flush usage tracker end-of-session metadata."""
        try:
            from cerberus.agents.global_usage_tracker import GLOBAL_USAGE_TRACKER

            GLOBAL_USAGE_TRACKER.end_session(final_cost=cost_usd)
        except Exception:
            pass

    def _clear_sensitive_buffers(self) -> bool:
        """Best-effort in-memory zeroization of sensitive temporary buffers."""
        try:
            # Known environment secrets are removed from process env view.
            for key in list(os.environ.keys()):
                upper = key.upper()
                if any(x in upper for x in ("KEY", "TOKEN", "SECRET", "PASSWORD", "PRIVATE")):
                    os.environ[key] = ""

            # Explicit tracked buffers (if any were registered).
            for buf in self._sensitive_buffers:
                for i in range(len(buf)):
                    buf[i] = 0
            self._sensitive_buffers.clear()
            return True
        except Exception:
            return False

    def _write_post_mortem(self, report: ShutdownReport) -> str:
        """Persist a concise post-mortem report in workspace folder."""
        root = self._active_workspace_root()
        out_dir = root / ".cerberus" / "reports"
        out_dir.mkdir(parents=True, exist_ok=True)

        stamp = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        path = out_dir / f"session_post_mortem_{stamp}.json"

        payload: Dict[str, Any] = {
            "generated_at": datetime.now(tz=timezone.utc).isoformat(),
            "mode": report.mode,
            "exit_code": report.exit_code,
            "engagement_duration_seconds": report.duration_seconds,
            "engagement_duration_hms": self._format_hms(report.duration_seconds),
            "total_cost_usd": report.cost_usd,
            "memory_synced": report.memory_synced,
            "workspace_synced": report.workspace_synced,
            "async_drained": report.async_drained,
            "orphaned_processes_cleaned": report.orphaned_processes_cleaned,
            "sensitive_buffers_cleared": report.sensitive_buffers_cleared,
            "critical_tool_failed": report.critical_tool_failed,
            "budget_exceeded": report.budget_exceeded,
            "notes": report.notes,
        }
        path.write_text(json.dumps(payload, indent=2))
        return str(path)

    def _render_summary(self, report: ShutdownReport) -> None:
        """Display commercial post-mortem summary in terminal."""
        engagement_start = self._engagement_start_time()
        total_duration = max(0.0, time.time() - engagement_start)

        table = Table(
            title="Session Post-Mortem",
            show_header=True,
            header_style="bold",
            box=box.ROUNDED,
        )
        table.add_column("Metric", style="cyan")
        table.add_column("Value", style="green")

        table.add_row("Shutdown mode", report.mode)
        table.add_row("Engagement duration", self._format_hms(total_duration))
        table.add_row("Total financial cost", f"${report.cost_usd:.6f}")
        table.add_row("Workspace report", report.workspace_report_path)
        table.add_row("Exit code", str(report.exit_code))

        console.print(table)

        # Highlight non-clean states for operational awareness.
        if report.exit_code != 0:
            reason = (
                "Budget exceeded" if report.exit_code == 2 else "Critical tool failure detected"
            )
            console.print(
                Panel(
                    reason,
                    title="[yellow]Non-Clean Session Status[/yellow]",
                    border_style="yellow",
                    box=box.ROUNDED,
                )
            )

    # -- public orchestration ----------------------------------------------

    async def shutdown(self, *, force: bool = False) -> ShutdownReport:
        """Run the full shutdown procedure and return a structured report."""
        report = ShutdownReport(started_at=self._start, mode="force" if force else "graceful")

        # Compute these early, before side effects.
        report.cost_usd = self._read_cost_usd()
        report.budget_exceeded = self._budget_exceeded()
        report.critical_tool_failed = self._critical_tool_failure_detected()

        if not force:
            mem_ok, mem_note = self._call_sync_or_save(self.memory, "memory")
            report.memory_synced = mem_ok
            report.notes.append(mem_note)

            ws_ok, ws_note = self._call_sync_or_save(self.workspace, "workspace")
            report.workspace_synced = ws_ok
            report.notes.append(ws_note)

            report.orphaned_processes_cleaned = await self._cleanup_orphaned_sessions()
            report.async_drained = await self._drain_async_tasks()
        else:
            report.notes.append("force mode: skipped memory/workspace sync and async drain")

        report.sensitive_buffers_cleared = self._clear_sensitive_buffers()

        # Always flush usage tracker and write post-mortem.
        self._finalize_usage_tracking(report.cost_usd)
        report.finished_at = time.time()
        report.workspace_report_path = self._write_post_mortem(report)

        self._render_summary(report)
        return report


# ---------------------------------------------------------------------------
# ExitCommand
# ---------------------------------------------------------------------------

class ExitCommand(FrameworkCommand):
    """Session shutdown command.

    Usage:
      /exit
      /exit --force

    Default behavior is graceful shutdown with full cleanup and persistence.
    Use ``--force`` to skip draining and sync steps in emergencies.
    """

    name = "exit"
    description = "Execute secure session shutdown procedure"
    aliases = ["/exit", "/quit", "/q"]

    def __init__(self) -> None:
        super().__init__()

    @property
    def help(self) -> str:
        return (
            "exit [--force]\n\n"
            "Performs session shutdown procedure:\n"
            "  - sync/save memory and workspace\n"
            "  - cleanup orphaned background tool processes\n"
            "  - drain async tasks\n"
            "  - clear sensitive temporary buffers\n"
            "  - print post-mortem and write report to workspace\n"
            "\n"
            "Flags:\n"
            "  --force   Skip graceful cleanup stages for emergency termination\n"
        )

    async def execute(self, args: List[str]) -> bool:
        force = any(a in ("--force", "-f") for a in args)

        orchestrator = ShutdownOrchestrator(
            workspace=self.workspace,
            memory=self.memory,
        )

        report = await orchestrator.shutdown(force=force)

        # Do not call sys.exit(); raising SystemExit preserves explicit codes
        # while keeping this module independent of legacy sys.exit flow.
        raise SystemExit(report.exit_code)


EXIT_COMMAND_INSTANCE = ExitCommand()
register_command(EXIT_COMMAND_INSTANCE)
